project:
  type: website
  output-dir: docs

website:
  title: "Duke SCOHP x NCAH Project"
  navbar:
    left:
      - href: about.qmd
        text: "About"
  search: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false