project:
  type: website

website:
  title: "NCAH Data Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Methods
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true