---
title: bootstrap cep
---

```{r}
#| label: import-libraries
library(tidyverse)
library(tidymodels)
cep_all <- read_csv("data/cep-all.csv")
glimpse(cep_all)
```

## Logistic Regression

```{r}
#| label: logistic-regression
cep_all |> 
  mutate(
    currently_participating_in_cep_district_wide = case_when(
      currently_participating_in_cep_district_wide == "A" ~"Yes", 
      is.na(currently_participating_in_cep_district_wide) ~ "No"
    )
  ) 

linear_reg() |> 
  fit(total_student_enrollment_in_participating_and_eligible_le_as ~ identified_student_percentage_isp, data = cep_all) |> 
  tidy()
  
```



## Stuff

```{r}
#| label: model-fit
cep_point <- cep_all |> 
  specify(currently_participating_in_cep ~ identified_student_percentage_isp) |> 
  fit()
cep_point
```

```{r}
#| label: model-bootstrap
cep_boot <- cep_all |> 
  specify(currently_participating_in_cep ~ identified_student_percentage_isp) |> 
  generate(reps = 1000, type = "bootstrap") |> 
  fit()
cep_boot
```

```{r}
#| label: cep-confidence-interval
get_confidence_interval(
  cep_boot,
  level = .95,
  type = "percentile",
  point_estimate = cep_point
)
```

